/**
 * web/web_ui.h — SDL30 Collector full single-page application
 *
 * 5 tabs:
 *   📏 Measure  — trigger SDL30, live HI/RL
 *   📋 Records  — edit/delete with RL recalc
 *   📁 Jobs     — create/manage/download
 *   📊 Report   — misclose + export
 *   ⚙️ Settings — method, limits, baud
 */
#pragma once

static const char WEB_UI_HTML[] =
"<!DOCTYPE html><html><head>"
"<meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1,viewport-fit=cover'>"
"<meta http-equiv='Cache-Control' content='no-store'>"
"<title>SDL30 Collector</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0;-webkit-tap-highlight-color:transparent}"
"body{font-family:sans-serif;background:#0d1117;color:#e6edf3;height:100vh;display:flex;flex-direction:column;overflow:hidden}"
"#header{background:#161b22;border-bottom:1px solid #30363d;padding:10px 16px;display:flex;align-items:center;justify-content:space-between;flex-shrink:0}"
"#header h1{font-size:16px;color:#39d5ff;font-weight:600}"
"#sdl-status{font-size:12px;padding:3px 10px;border-radius:12px;font-weight:500}"
".st-ok{background:#0d4429;color:#3fb950}"
".st-err{background:#3d1c1c;color:#f85149}"
"#content{flex:1;overflow-y:auto;padding:12px;padding-bottom:calc(80px + env(safe-area-inset-bottom,0px))}"
"#tabs{position:fixed;bottom:0;left:0;right:0;background:#161b22;"
      "border-top:1px solid #30363d;display:flex;z-index:100;"
      "padding-bottom:env(safe-area-inset-bottom,0px)}"
".tab{flex:1;padding:8px 4px;text-align:center;cursor:pointer;font-size:10px;color:#8b949e;border:none;background:none}"
".tab.active{color:#39d5ff;border-top:2px solid #39d5ff}"
".tab .icon{font-size:18px;display:block}"
".card{background:#161b22;border:1px solid #30363d;border-radius:10px;padding:14px;margin-bottom:12px}"
".card-title{font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:#8b949e;margin-bottom:10px}"
".row{display:flex;justify-content:space-between;align-items:center;padding:8px 0;border-bottom:1px solid #21262d}"
".row:last-child{border-bottom:none}"
".lbl{font-size:14px;color:#e6edf3}"
".hint{font-size:11px;color:#8b949e;margin-top:2px}"
".val{font-size:14px;color:#39d5ff;font-weight:500}"
".big{font-size:28px;font-weight:700;color:#39d5ff}"
".ok{color:#3fb950}.err{color:#f85149}.warn{color:#d29922}"
"button{border:none;cursor:pointer;font-family:sans-serif;border-radius:8px;padding:10px 18px;font-size:14px;font-weight:500}"
".btn-primary{background:#1f6feb;color:#fff;width:100%;margin-top:8px;padding:14px}"
".btn-primary:disabled{background:#333;color:#666}"
".btn-sm{background:#21262d;color:#e6edf3;border:1px solid #30363d;padding:6px 12px;font-size:12px;margin:2px}"
".btn-danger{background:#3d1c1c;color:#f85149;border:1px solid #6e2424}"
".btn-success{background:#0d4429;color:#3fb950;border:1px solid #176f2c}"
".btn-row{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}"
"input,select{background:#0d1117;border:1px solid #30363d;color:#e6edf3;border-radius:6px;padding:8px 10px;font-size:14px;width:100%;margin-top:4px}"
"input[type=number]{width:90px;text-align:right}"
".sight-row{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin:10px 0}"
".sight-btn{padding:12px;border:1px solid #30363d;border-radius:8px;text-align:center;cursor:pointer;background:#0d1117;font-size:14px;font-weight:600;color:#8b949e}"
".sight-btn.active{border:2px solid #39d5ff;color:#39d5ff;background:#0d2135}"
"table{width:100%;border-collapse:collapse;font-size:12px}"
"th{text-align:left;padding:6px 4px;color:#8b949e;border-bottom:1px solid #30363d;font-weight:500}"
"td{padding:6px 4px;border-bottom:1px solid #21262d}"
"tr.is td{color:#e6edf3}"
"tr.orphan td{color:#666666}"
"tr.orphan td:first-child::before{content:'(!)';color:#d29922}"
"td.setup-num{font-weight:700}"
".note-dot{color:#d29922;font-size:10px;vertical-align:super;cursor:pointer}"
".misclose-ok{color:#3fb950;font-size:24px;font-weight:700}"
".misclose-warn{color:#d29922;font-size:24px;font-weight:700}"
".misclose-err{color:#f85149;font-size:24px;font-weight:700}"
".toggle{position:relative;width:40px;height:22px;display:inline-block}"
".toggle input{opacity:0;width:0;height:0}"
".tslider{position:absolute;inset:0;background:#30363d;border-radius:11px;transition:.2s}"
".tslider:before{content:'';position:absolute;width:16px;height:16px;left:3px;top:3px;background:#fff;border-radius:50%;transition:.2s}"
"input:checked+.tslider{background:#1f6feb}"
"input:checked+.tslider:before{transform:translateX(18px)}"
".method-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px}"
".method-btn{padding:10px;border:1px solid #30363d;border-radius:8px;text-align:center;cursor:pointer;background:#0d1117}"
".method-btn.active{border:2px solid #39d5ff;background:#0d2135}"
".method-name{font-size:16px;font-weight:700;color:#39d5ff}"
".method-desc{font-size:11px;color:#8b949e;margin-top:2px}"
"#toast{position:fixed;top:60px;left:50%;transform:translateX(-50%);"
        "background:#161b22;border:1px solid #30363d;border-radius:8px;"
        "padding:10px 20px;font-size:13px;z-index:200;display:none;white-space:nowrap}"
".warn-banner{background:#2d1f00;border:1px solid #d29922;border-radius:8px;"
              "padding:10px;margin-bottom:10px;color:#d29922;font-size:13px;display:none}"
".storage-bar{background:#21262d;border-radius:4px;height:8px;margin-top:6px}"
".storage-fill{background:#1f6feb;border-radius:4px;height:8px;transition:.3s}"
"</style></head><body>"

"<div id='header'>"
"<h1>SDL30 Collector</h1>"
"<div id='sdl-status' class='st-err'>OFFLINE</div>"
"</div>"

"<div id='toast'></div>"

"<div id='content'>"

"<!-- TAB 0: MEASURE -->"
"<div id='tab0'>"
"<div class='card'>"
"<div class='card-title'>Current status</div>"
"<div class='row'><span class='lbl'>Job</span><span class='val' id='m-job'>---</span></div>"
"<div class='row'><span class='lbl'>Height of Instrument (HI)</span><span class='val' id='m-hi'>---.----m</span></div>"
"<div class='row'><span class='lbl'>Reduced Level (RL)</span><span class='val' id='m-rl'>---.----m</span></div>"
"<div class='row'><span class='lbl'>Readings</span><span class='val' id='m-pts'>0</span></div>"
"<div class='row'><span class='lbl'>Points</span><span class='val' id='m-fpts'>0</span></div>"
"</div>"
"<div id='insert-banner' style='display:none;background:#2d1f00;border:1px solid #d29922;"
"border-radius:8px;padding:10px;margin-bottom:8px;color:#d29922;font-size:13px'>"
"<div style='display:flex;justify-content:space-between;align-items:center'>"
"<div>INSERT MODE &mdash; after <b id='insert-prev-name'>---</b></div>"
"<button onclick='cancelInsert()' style='background:#3d1c1c;color:#f85149;"
"border:1px solid #6e2424;border-radius:6px;padding:4px 10px;font-size:12px;cursor:pointer'>Done</button>"
"</div></div>"

"<div class='card'>"
"<div style='display:flex;justify-content:space-between;align-items:center'>"
"<div class='card-title' id='sight-card-title' style='margin:0'>Sight type</div>"
"<div id='method-badge' style='font-size:12px;color:#58a6ff;font-weight:700'>BF</div>"
"</div>"
"<div id='dblr-steps' style='display:none;margin-top:10px'>"
"<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:8px'>"
"<div style='display:flex;gap:6px;width:100%'>"
"<div id='dblr-lbl-1' style='flex:1;text-align:center;padding:10px 4px;border-radius:8px;background:#21262d'>"
"<div style='font-size:28px;font-weight:700;color:#8b949e' id='dblr-ch-1'>B</div>"
"<div style='font-size:11px;color:#8b949e;margin-top:2px' id='dblr-val-1'></div>"
"</div>"
"<div id='dblr-lbl-2' style='flex:1;text-align:center;padding:10px 4px;border-radius:8px;background:#21262d'>"
"<div style='font-size:28px;font-weight:700;color:#8b949e' id='dblr-ch-2'>F</div>"
"<div style='font-size:11px;color:#8b949e;margin-top:2px' id='dblr-val-2'></div>"
"</div>"
"<div id='dblr-lbl-3' style='flex:1;text-align:center;padding:10px 4px;border-radius:8px;background:#21262d'>"
"<div style='font-size:28px;font-weight:700;color:#8b949e' id='dblr-ch-3'>F</div>"
"<div style='font-size:11px;color:#8b949e;margin-top:2px' id='dblr-val-3'></div>"
"</div>"
"<div id='dblr-lbl-4' style='flex:1;text-align:center;padding:10px 4px;border-radius:8px;background:#21262d'>"
"<div style='font-size:28px;font-weight:700;color:#8b949e' id='dblr-ch-4'>B</div>"
"<div style='font-size:11px;color:#8b949e;margin-top:2px' id='dblr-val-4'></div>"
"</div>"
"</div>"
"<span id='dblr-step-lbl' style='font-size:12px;color:#8b949e'>Step 1/4</span>"
"</div>"
"<div style='display:flex;gap:4px;margin-bottom:8px'>"
"<div id='ds1' style='flex:1;height:6px;border-radius:3px;background:#21262d'></div>"
"<div id='ds2' style='flex:1;height:6px;border-radius:3px;background:#21262d'></div>"
"<div id='ds3' style='flex:1;height:6px;border-radius:3px;background:#21262d'></div>"
"<div id='ds4' style='flex:1;height:6px;border-radius:3px;background:#21262d'></div>"
"</div>"
"<div id='dblr-readings' style='display:flex;justify-content:space-around;font-size:11px;color:#8b949e;font-family:monospace;margin-top:4px'></div>"
"<div id='dblr-result' style='display:none;margin-top:8px;padding:8px;border-radius:8px;text-align:center;font-weight:700'></div>"
"<button id='dblr-repeat-btn' onclick='dblrRepeat()' style='display:none;width:100%;margin-top:8px;padding:10px;background:#3d1c1c;color:#f85149;border:1px solid #6e2424;border-radius:8px'>RPT Repeat Setup</button>"
"</div>"
"<div id='sight-leveling' class='sight-row'>"
"<div class='sight-btn active' id='sb-BS' onclick='setSight(\"BS\")'>BS<div style='font-size:10px;color:#8b949e;font-weight:400'>Backsight</div></div>"
"<div class='sight-btn' id='sb-FS' onclick='setSight(\"FS\")'>FS<div style='font-size:10px;color:#8b949e;font-weight:400'>Foresight</div></div>"
"</div>"
"<div id='sight-setout' class='sight-row' style='display:none'>"
"<div class='sight-btn active' id='sb-SO-BS' onclick='setSight(\"BS\")'>BS<div style='font-size:10px;color:#8b949e;font-weight:400'>Backsight</div></div>"
"<div class='sight-btn' id='sb-SO-FS' onclick='setSight(\"FS\")'>FS<div style='font-size:10px;color:#8b949e;font-weight:400'>Foresight</div></div>"
"<div class='sight-btn' id='sb-SO-IS' onclick='setSight(\"IS\")'>IS<div style='font-size:10px;color:#8b949e;font-weight:400'>Peg check</div></div>"
"</div>"
"<div id='setout-fields' style='display:none;margin-top:8px'>"
"<div class='row'><span class='lbl'>Design RL</span>"
"<div style='display:flex;align-items:center;gap:6px'>"
"<input type='number' id='so-design-rl' step='0.001' placeholder='e.g. 99.500' style='width:110px'>"
"<span style='font-size:12px;color:#8b949e'>m</span></div></div>"
"<div id='so-cutfill' style='text-align:center;padding:6px 0;font-size:13px;color:#8b949e'>Enter design RL above</div>"
"<div id='so-adjust' style='text-align:center;font-size:13px;display:none'></div>"
"</div>"
"</div>"
"<button onclick='clearSetup()' style='width:100%;padding:8px;background:transparent;"
"border:1px solid #30363d;border-radius:8px;color:#8b949e;font-size:12px;cursor:pointer;"
"margin-bottom:8px'>Clear current setup</button>"
"<div class='card'>"
"<div class='card-title'>Measurement</div>"
"<div id='warn-banner' class='warn-banner'></div>"
"<div id='fs-name-row' style='display:none;margin-bottom:8px'>"
"<div class='row' style='border-bottom:none'>"
"<span class='lbl' style='font-size:12px;color:#8b949e'>Point name</span>"
"<input type='text' id='fs-name-input' maxlength='23' autocomplete='off' autocorrect='off' "
"spellcheck='false' "
"style='width:130px;background:#0d1117;color:#e6edf3;border:1px solid #58a6ff;"
"border-radius:6px;padding:5px 8px;font-size:14px;font-family:monospace'>"
"</div>"
"</div>"
"<div id='meas-result' style='text-align:center;padding:8px 0'>"
"<div style='color:#8b949e;font-size:13px'>Ready to measure</div>"
"</div>"
"<button class='btn-primary' id='btn-measure' onclick='doMeasure()'>MEASURE</button>"
"<button id='btn-remeasure' onclick='reMeasure()'"
" style='display:none;width:100%;margin-top:6px;padding:10px;"
"background:#21262d;color:#d29922;border:1px solid #d29922;"
"border-radius:8px;font-size:13px;cursor:pointer'>&#x21BA; Re-measure last reading</button>"
"</div>"
"</div>"

"<!-- TAB 1: RECORDS -->"
"<div id='tab1' style='display:none'>"

"<!-- Section 1: Running summary side by side -->"
"<div style='display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:12px'>"
"<div class='card' style='margin-bottom:0'>"
"<div class='card-title'>Arithmetic</div>"
"<div class='row'><span class='lbl' style='font-size:11px'>&#x3A3; BS</span><span class='val' style='font-size:11px' id='rc-sbs'>---</span></div>"
"<div class='row'><span class='lbl' style='font-size:11px'>&#x3A3; FS</span><span class='val' style='font-size:11px' id='rc-sfs'>---</span></div>"
"<div class='row'><span class='lbl' style='font-size:11px'>&#x3A3;BS&#x2212;&#x3A3;FS</span><span class='val' style='font-size:11px' id='rc-diff'>---</span></div>"
"<div class='row'><span class='lbl' style='font-size:11px' id='rc-stn-lbl'>BS-FS</span><span id='rc-stn' style='font-size:11px;font-weight:600'>---</span></div>"
"<div class='row'><span class='lbl' style='font-size:11px'>1st Elev.</span><span class='val' style='font-size:11px' id='rc-frl'>---</span></div>"
"<div class='row'><span class='lbl' style='font-size:11px' id='rc-arl-lbl'>Last RL</span><span class='val' style='font-size:11px' id='rc-arl'>---</span></div>"
"<div style='text-align:center;padding:6px 0;font-size:14px;font-weight:700' id='rc-chk'>---</div>"
"</div>"
"<div class='card' style='margin-bottom:0'>"
"<div class='card-title'>Dist balance</div>"
"<div class='row'><span class='lbl' style='font-size:11px'>&#x3A3; BS dist</span><span class='val' style='font-size:11px' id='rd-sbs'>---</span></div>"
"<div class='row'><span class='lbl' style='font-size:11px'>&#x3A3; FS dist</span><span class='val' style='font-size:11px' id='rd-sfs'>---</span></div>"
"<div class='row'><span class='lbl' style='font-size:11px'>Diff</span><span class='val' style='font-size:11px' id='rd-diff'>---</span></div>"
"<div class='row'><span class='lbl' style='font-size:11px'>Limit</span><span class='val' style='font-size:11px' id='rd-lim'>---</span></div>"
"<div style='text-align:center;padding:6px 0;font-size:14px;font-weight:700' id='rd-stat'>---</div>"
"</div>"
"</div>"

"<!-- Section 2: Records table -->"
"<div class='card'>"
"<div class='card-title'>Observation records</div>"
"<div style='overflow-x:auto'>"
"<table>"
"<thead><tr><th>#</th><th>Stn</th><th>Name</th><th>Sight</th><th>Staff(m)</th><th>Dist(m)</th><th>HI(m)</th><th>RL(m)</th><th>&#x1F4AC;</th><th></th></tr></thead>"
"<tbody id='rec-tbody'><tr><td colspan='8' style='text-align:center;color:#8b949e;padding:20px'>No records yet</td></tr></tbody>"
"</table>"
"</div>"
"</div>"
"</div>"

"<!-- TAB 2: JOBS -->"
"<div id='tab2' style='display:none'>"
"<div class='card'>"
"<div class='card-title'>Active job</div>"
"<div class='row'><span class='lbl'>Job name</span><span class='val' id='j-name'>---</span></div>"
"<div class='row'><span class='lbl'>Benchmark RL</span><span class='val' id='j-bm'>---</span></div>"
"<div class='row'><span class='lbl'>Points</span><span class='val' id='j-pts'>0</span></div>"
"<div class='btn-row'>"
"<button class='btn-sm btn-success' onclick='downloadCSV()'>CSV</button>"
"<button class='btn-sm btn-success' onclick='downloadM5()'>M5/Zeiss</button>"
"</div>"
"</div>"
"<div class='card'>"
"<div class='card-title'>Set benchmark RL</div>"
"<input type='number' id='new-bm' step='0.001' placeholder='e.g. 100.000'>"
"<button class='btn-primary' onclick='setBench()'>Apply Benchmark RL</button>"
"</div>"
"<div class='card'>"
"<div class='card-title'>Create new job</div>"
"<input type='text' id='new-job-name' placeholder='Job name e.g. RWY28L_2026' maxlength='23'>"
"<input type='number' id='new-job-bm' step='0.001' placeholder='Benchmark RL (optional - uses current if blank)'>"
"<button class='btn-primary' onclick='newJob()'>Create Job</button>"
"</div>"
"<div class='card'>"
"<div class='card-title'>Storage</div>"
"<div class='row'><span class='lbl'>Flash used</span><span class='val' id='j-storage'>---</span></div>"
"<div class='storage-bar'><div class='storage-fill' id='j-storage-bar' style='width:0%'></div></div>"
"</div>"
"<div class='card'>"
"<div class='card-title'>All jobs</div>"
"<div id='job-list'><div style='color:#8b949e;text-align:center;padding:12px'>Loading...</div></div>"
"</div>"
"</div>"

"<!-- TAB 3: REPORT -->"
"<div id='tab3' style='display:none'>"
"<div class='card'>"
"<div class='card-title'>Closing benchmark</div>"
"<input type='number' id='closing-rl' step='0.001' placeholder='Enter closing BM elevation'>"
"<button class='btn-primary' onclick='calcMisclose()'>Calculate Misclosure</button>"
"</div>"
"<div class='card' id='report-card' style='display:none'>"
"<div class='card-title'>Misclosure report</div>"
"<div style='font-size:11px;color:#8b949e;margin-bottom:8px'>Opening BM + &#x3A3;BS - &#x3A3;FS = Comp. Elev</div>"
"<div class='row'><span class='lbl'>&#x3A3; BS</span><span class='val' id='rpt-bs'>---</span></div>"
"<div class='row'><span class='lbl'>&#x3A3; FS</span><span class='val' id='rpt-fs'>---</span></div>"
"<div class='row'><span class='lbl'>&#x394;Elev</span><span class='val' id='rpt-dh'>---</span></div>"
"<div class='row'><span class='lbl'>Comp. Elev</span><span class='val' id='rpt-chk'>---</span></div>"
"<div class='row'><span class='lbl'>Closing BM</span><span class='val' id='rpt-cel'>---</span></div>"
"<div class='row'><span class='lbl'>Misclosure</span><span id='rpt-mc' style='font-weight:600'>---</span></div>"
"<div class='row'><span class='lbl'>Points</span><span class='val' id='rpt-pts'>---</span></div>"
"<div class='row'><span class='lbl'>Readings</span><span class='val' id='rpt-rdg'>---</span></div>"
"</div>"
"<div class='card' id='dist-card' style='display:none'>"
"<div class='card-title'>Distance report</div>"
"<div style='font-size:11px;color:#8b949e;margin-bottom:8px'>&#x3A3;BS Dist + &#x3A3;FS Dist = Total Dist</div>"
"<div class='row'><span class='lbl'>&#x3A3; BS dist</span><span class='val' id='rpt-bsd'>---</span></div>"
"<div class='row'><span class='lbl'>&#x3A3; FS dist</span><span class='val' id='rpt-fsd'>---</span></div>"
"<div class='row'><span class='lbl'>Dist Balance</span><span id='rpt-dcd' style='font-weight:600'>---</span></div>"
"<div class='row'><span class='lbl'>Total dist</span><span class='val' id='rpt-td'>---</span></div>"
"</div>"
"<div class='card'>"
"<div class='card-title'>Report export</div>"
"<div class='btn-row'>"
"<button class='btn-sm' onclick='downloadReportCSV()'>CSV</button>"
"<button class='btn-sm' onclick='downloadReportHTML()'>HTML</button>"
"</div>"
"</div>"
"</div>"

"<!-- TAB 4: SETTINGS -->"
"<div id='tab4' style='display:none'>"
"<div class='card'>"
"<div class='card-title'>Observation method</div>"
"<div class='method-grid' id='method-grid'>"
"<div class='method-btn active' id='mb-0' onclick='setMethod(0)'><div class='method-name'>BF</div><div class='method-desc'>Basic · fast</div></div>"
"<div class='method-btn' id='mb-1' onclick='setMethod(1)'><div class='method-name'>BFFB</div><div class='method-desc'>3rd order</div></div>"
"<div class='method-btn' id='mb-4' onclick='setMethod(4)' style='grid-column:span 2'><div class='method-name'>SET-OUT</div><div class='method-desc'>Construction · BS+IS pegs</div></div>"
"</div>"
"</div>"
"<div class='card'>"
"<div class='card-title'>Limits / tests</div>"
"<div class='row'><div><div class='lbl'>Max station diff</div><div class='hint'>|BS−FS| per setup</div></div>"
"<div style='display:flex;align-items:center;gap:6px'><input type='number' id='s-maxst' value='2.0' step='0.5' min='0' style='width:70px' onchange='saveSettings()'><span style='font-size:12px;color:#8b949e'>mm</span></div></div>"
"<div class='row'><div><div class='lbl'>Max dist diff</div><div class='hint'>|dBS−dFS| per setup</div></div>"
"<div style='display:flex;align-items:center;gap:6px'><input type='number' id='s-maxdd' value='5.0' step='1' min='0' style='width:70px' onchange='saveSettings()'><span style='font-size:12px;color:#8b949e'>m</span></div></div>"
"<div class='row'><div><div class='lbl'>Max cum dist diff</div><div class='hint'>ΣdBS−ΣdFS for run</div></div>"
"<div style='display:flex;align-items:center;gap:6px'><input type='number' id='s-maxcd' value='10.0' step='1' min='0' style='width:70px' onchange='saveSettings()'><span style='font-size:12px;color:#8b949e'>m</span></div></div>"
"<div class='row'><div><div class='lbl'>Min sighting height</div><div class='hint'>Staff reading minimum</div></div>"
"<div style='display:flex;align-items:center;gap:6px'><input type='number' id='s-minsh' value='0.3' step='0.05' min='0' style='width:70px' onchange='saveSettings()'><span style='font-size:12px;color:#8b949e'>m</span></div></div>"
"<div class='row'><div><div class='lbl'>Max sighting dist</div><div class='hint'>SDL30 to staff limit</div></div>"
"<div style='display:flex;align-items:center;gap:6px'><input type='number' id='s-maxsd' value='50' step='5' min='1' style='width:70px' onchange='saveSettings()'><span style='font-size:12px;color:#8b949e'>m</span></div></div>"
"</div>"
"<div class='card'>"
"<div class='card-title'>Alerts</div>"
"<div class='row'><div><div class='lbl'>Alert on exceed</div><div class='hint'>Warn before saving</div></div>"
"<label class='toggle'><input type='checkbox' id='s-alert' checked onchange='saveSettings()'><span class='tslider'></span></label></div>"
"<div class='row'><div><div class='lbl'>Block save on exceed</div><div class='hint'>Prevent bad readings</div></div>"
"<label class='toggle'><input type='checkbox' id='s-block' onchange='saveSettings()'><span class='tslider'></span></label></div>"
"</div>"
"<div class='card'>"
"<div class='card-title'>Baud rate</div>"
"<div class='row'><div class='lbl'>SDL30 baud rate</div>"
"<select id='s-baud' style='width:auto' onchange='saveSettings()'><option value='2400' selected>2400</option><option value='1200'>1200</option></select>"
"</div>"
"</div>"
"<div style='font-size:11px;color:#8b949e;text-align:center;padding:4px'>Settings save automatically</div>"
"</div>"

"</div>"

"<!-- CONFIRM MODAL -->"
"<div id='modal' style='display:none;position:fixed;inset:0;background:rgba(0,0,0,0.75);z-index:300;align-items:center;justify-content:center'>"
"<div style='background:#161b22;border:1px solid #30363d;border-radius:12px;padding:20px;margin:0 20px;max-width:400px'>"
"<div id='modal-msg' style='font-size:15px;color:#e6edf3;margin-bottom:16px;line-height:1.5'></div>"
"<div style='display:flex;gap:8px'>"
"<button id='modal-ok' class='btn-primary' style='flex:1;margin:0;padding:10px'>OK</button>"
"<button id='modal-cancel' style='flex:1;padding:10px;background:#21262d;color:#e6edf3;border:1px solid #30363d;border-radius:8px;cursor:pointer'>Cancel</button>"
"</div></div></div>"

"<!-- TAB BAR -->"
"<div id='tabs'>"
"<button class='tab active' id='t0' onclick='showTab(0)'><span class='icon'>📏</span>Measure</button>"
"<button class='tab' id='t1' onclick='showTab(1)'><span class='icon'>📋</span>Records</button>"
"<button class='tab' id='t2' onclick='showTab(2)'><span class='icon'>📁</span>Jobs</button>"
"<button class='tab' id='t3' onclick='showTab(3)'><span class='icon'>📊</span>Report</button>"
"<button class='tab' id='t4' onclick='showTab(4)'><span class='icon'>⚙️</span>Settings</button>"
"</div>"

"<script>"
"var curTab=0, nextSight='BS', measuring=false, settings={obs_method:0}, cachedRecords=[], cachedReport=null;"
"var s_dblr_step=0;"
"var lastMeasuredIndex=0,lastMeasuredSight='BS';"
"var DBLR_LABELS=[['BS1','FS1','FS2','BS2'],['BS1','FS1','BS2','FS2'],['BS1','BS2','FS1','FS2']];"
"var DBLR_METHODS=['BFFB','BFFB','BFFB'];"
"var sumDist=0, prevDist=0;"

// ── Tab switching ──
"function showTab(n){"
"  for(var i=0;i<5;i++){"
"    document.getElementById('tab'+i).style.display=i===n?'block':'none';"
"    document.getElementById('t'+i).classList.toggle('active',i===n);"
"  }"
"  curTab=n;"
"  if(n===1)loadRecords();"
"  if(n===2)loadJobs();"
"  if(n===3){var bm=document.getElementById('j-bm').textContent;document.getElementById('closing-rl').value=bm;}"
"  if(n===4){if(!settings||settings.obs_method===undefined){loadSettings();}else{setMethodUI(settings.obs_method);}}"
"}"

// ── Toast ──
"function showToast(msg,ms){"
"  var t=document.getElementById('toast');"
"  t.textContent=msg;t.style.display='block';"
"  setTimeout(function(){t.style.display='none';},ms||2500);"
"}"

// ── Status refresh ──
"async function refreshStatus(){"
"  try{"
"    var r=await fetch('/api/status');"
"    var d=await r.json();"
"    var el=document.getElementById('sdl-status');"
"    if(d.sdl_ok){el.textContent='CONNECTED';el.className='st-ok';}"
"    else{el.textContent='OFFLINE';el.className='st-err';}"
"    document.getElementById('m-job').textContent=d.job||'---';"
"    document.getElementById('m-hi').textContent=(d.hi||0).toFixed(4)+'m';"
"    document.getElementById('m-rl').textContent=(d.rl||0).toFixed(4)+'m';"
"    document.getElementById('m-pts').textContent=d.readings||d.points||0;"
"    document.getElementById('m-fpts').textContent=d.points||0;"
"    document.getElementById('j-name').textContent=d.job||'---';"
"    document.getElementById('j-bm').textContent=(d.bench_rl||0).toFixed(4)+'m';"
"    document.getElementById('j-pts').textContent=d.points||0;"
"    if(d.next_sight)setSightUI(d.next_sight);"
"    var m2=d.obs_method||0;"
"    var mb=document.getElementById('method-badge');"
"    var sl=document.getElementById('sight-leveling');"
"    var methods=['BF','BFFB','BFFB','BFFB','SET-OUT'];"
"    if(mb)mb.textContent=methods[m2]||'BF';"
"    var ds=document.getElementById('dblr-steps');"
"    if(m2>=1&&m2<=3){"
"      if(sl)sl.style.display='none';"
"      if(ds)ds.style.display='block';"
"      var mi2=m2-1;"
"      var ltrs=[['B','F','F','B'],['B','F','B','F'],['B','B','F','F']];"
"      var step2=d.dblr_step||0;"
"      var curStep=(step2>=5||step2===0)?1:step2;"
"      var vals=[d.bs1,d.fs1,d.fs2,d.bs2];"
"      for(var li=1;li<=4;li++){"
"        var el=document.getElementById('dblr-lbl-'+li);"
"        var ch=document.getElementById('dblr-ch-'+li);"
"        var vl=document.getElementById('dblr-val-'+li);"
"        if(!el)continue;"
"        if(ch)ch.textContent=ltrs[mi2][li-1];"
"        if(vl)vl.textContent=(li<curStep&&vals[li-1])?vals[li-1].toFixed(4)+'m':'';"
"        if(li===curStep){el.style.background='#1f6feb';if(ch)ch.style.color='#ffffff';}"
"        else if(li<curStep){el.style.background='#0d2818';if(ch)ch.style.color='#3fb950';}"
"        else{el.style.background='#21262d';if(ch)ch.style.color='#8b949e';}"
"      }"
"    }else{"
"      if(sl)sl.style.display='grid';"
"      if(ds)ds.style.display='none';"
"    }"
"    var ib=document.getElementById('insert-banner');"
"    if(ib){"
"      if(d.insert_mode){"
"        ib.style.display='block';"
"        var ipn=document.getElementById('insert-prev-name');"
"        if(ipn)ipn.textContent=d.insert_prev_name||'(start)';"
"        var rb=document.getElementById('btn-remeasure');"
"        if(rb){rb.style.display='none';lastMeasuredIndex=0;}"
"      }else{"
"        ib.style.display='none';"
"      }"
"    }"
"    if(d.flash_total&&d.flash_used){"
"      var pct=Math.round(d.flash_used/d.flash_total*100);"
"      document.getElementById('j-storage').textContent="
"        Math.round(d.flash_used/1024)+'KB / '+Math.round(d.flash_total/1024)+'KB ('+pct+'%)';"
"      document.getElementById('j-storage-bar').style.width=pct+'%';"
"    }"
"  }catch(e){}"
"}"

// ── Sight selector ──
"function setSightUI(s){"
"  nextSight=s;"
"  var m=(settings&&settings.obs_method!==undefined)?settings.obs_method:0;"
"  if(m===4){"
"    ['BS','FS','IS'].forEach(function(x){"
"      var el=document.getElementById('sb-SO-'+x);"
"      if(el)el.classList.toggle('active',x===s);"
"    });"
"  }else{"
"    ['BS','FS'].forEach(function(x){"
"      var el=document.getElementById('sb-'+x);"
"      if(el)el.classList.toggle('active',x===s);"
"    });"
"  }"
"}"
"function setSight(s){"
"  setSightUI(s);"
"  fetch('/api/sight',{method:'POST',headers:{'Content-Type':'application/json'},"
"    body:JSON.stringify({sight:s})});"
"}"

// ── Measure ──
"document.addEventListener('input',function(e){"
"  if(e.target.id==='so-design-rl'){updateCutFill();}"
"});"
"function updateCutFill(){"
"  var hi=parseFloat(document.getElementById('m-hi').textContent);"
"  var drl=parseFloat(document.getElementById('so-design-rl').value);"
"  if(isNaN(hi)||isNaN(drl)){return;}"
"  var reqStaff=hi-drl;"
"  var cfEl=document.getElementById('so-cutfill');"
"  cfEl.innerHTML='Required staff: <b>'+reqStaff.toFixed(4)+'m</b>';"
"}"
"function updateSetoutResult(measStaff,hi){"
"  var drl=parseFloat(document.getElementById('so-design-rl').value);"
"  if(isNaN(drl))return;"
"  var actualRL=hi-measStaff;"
"  var adjust=drl-actualRL;"
"  var adjEl=document.getElementById('so-adjust');"
"  adjEl.style.display='block';"
"  var dir=adjust>0?'RAISE':'LOWER';"
"  var col=Math.abs(adjust)<0.005?'#3fb950':'#d29922';"
"  adjEl.innerHTML='Peg adjust: <b style=\"color:'+col+'\">'"
"    +(Math.abs(adjust)*1000).toFixed(1)+'mm '+dir+'</b>';"
"}"
"function checkLimits(staff,dist,s){"
"  var warns=[];"
"  if(staff<settings.min_sight_ht)warns.push('Staff '+staff.toFixed(4)+'m below min '+settings.min_sight_ht+'m');"
"  if(dist>settings.max_sight_dist)warns.push('Distance '+dist.toFixed(3)+'m exceeds max '+settings.max_sight_dist+'m');"
"  return warns;"
"}"
"function suggestNextTpName(){"
"  var max=0;"
"  cachedRecords.forEach(function(r){"
"    var m=r.name&&r.name.match(/^TP(\\d+)$/);"
"    if(m){var n=parseInt(m[1]);if(n>max)max=n;}"
"  });"
"  return 'TP'+String(max+1).padStart(3,'0');"
"}"
"function showFsNameField(){"
"  var row=document.getElementById('fs-name-row');"
"  var inp=document.getElementById('fs-name-input');"
"  inp.value=suggestNextTpName();"
"  row.style.display='block';"
"  inp.focus();inp.select();"
"}"
"function hideFsNameField(){"
"  document.getElementById('fs-name-row').style.display='none';"
"}"
"async function doMeasure(){"
"  if(measuring)return;"
"  measuring=true;"
"  lastMeasuredIndex=0;"
"  document.getElementById('btn-remeasure').style.display='none';"
"  var btn=document.getElementById('btn-measure');"
"  btn.disabled=true;btn.textContent='Measuring...';"
"  document.getElementById('warn-banner').style.display='none';"
"  document.getElementById('meas-result').innerHTML="
"    '<div style=\"color:#8b949e\">Reading SDL30...</div>';"
"  var m=(settings&&settings.obs_method!==undefined)?settings.obs_method:0;"
"  var isFsShot=(m===0&&nextSight==='FS')||(m>=1&&m<=3&&s_dblr_step===2);"
"  var ptName=isFsShot?(document.getElementById('fs-name-input').value.trim()||''):'';"
"  try{"
"    var payload={sight:nextSight};"
"    if(ptName)payload.name=ptName;"
"    var r=await fetch('/api/measure',{method:'POST',"
"      headers:{'Content-Type':'application/json'},"
"      body:JSON.stringify(payload)});"
"    var d=await r.json();"
"    if(d.ok){"
"      if(m>=1&&m<=3){s_dblr_step=d.dblr_step||0;updateDblrCard(d,m);refreshStatus();loadRecords();}"
"      else{refreshStatus();loadRecords();}"
"      var warns=checkLimits(d.staff,d.distance,nextSight);"
"      if(warns.length&&settings.alert_on_exceed){"
"        var wb=document.getElementById('warn-banner');"
"        wb.textContent='(!)'+warns.join(' | ');"
"        wb.style.display='block';"
"      }"
"      document.getElementById('meas-result').innerHTML="
"        '<div class=\"big\">'+d.staff.toFixed(4)+'m</div>'"
"        +'<div style=\"color:#8b949e;font-size:13px;margin-top:4px\">"
"          Staff (Rh) &nbsp;|&nbsp; Dist: '+d.distance.toFixed(3)+'m</div>'"
"        +'<div style=\"color:#3fb950;font-size:13px;margin-top:6px\">"
"          RL: '+d.rl.toFixed(4)+'m &nbsp;|&nbsp; HI: '+d.hi.toFixed(4)+'m</div>'"
"        +'<div style=\"font-size:12px;color:#8b949e;margin-top:4px\">"
"          Point #'+d.index+' ['+d.sight+'] '+(d.name||'')+'</div>';"
"      if(m===4){"
"        if(nextSight==='BS')setSightUI('IS');"
"        if(nextSight==='IS'){updateSetoutResult(d.staff,d.hi);setSightUI('IS');}"
"        if(nextSight==='FS')setSightUI('BS');"
"      }else if(m===0){"
"        if(nextSight==='BS'){setSightUI('FS');showFsNameField();}"
"        else if(nextSight==='FS'){setSightUI('BS');hideFsNameField();}"
"      }else{"
"        if(s_dblr_step===2)showFsNameField();"
"        else hideFsNameField();"
"      }"
"      var isBFFBFail=(m>=1&&m<=3&&d.dblr_step>=5&&!d.passed);"
"      if(!isBFFBFail){"
"        lastMeasuredIndex=d.index;"
"        lastMeasuredSight=d.sight||nextSight;"
"        document.getElementById('btn-remeasure').style.display='block';"
"      }"
"    }else{"
"      document.getElementById('meas-result').innerHTML="
"        '<div class=\"err\">'+( d.error||'Timeout - check staff & SDL30')+'</div>';"
"    }"
"  }catch(e){"
"    document.getElementById('meas-result').innerHTML='<div class=\"err\">Error: '+e+'</div>';"
"  }"
"  btn.disabled=false;btn.textContent='MEASURE';measuring=false;"
"}"

// ── Re-measure ──
"async function reMeasure(){"
"  if(!lastMeasuredIndex)return;"
"  var idx=lastMeasuredIndex,sight=lastMeasuredSight;"
"  lastMeasuredIndex=0;"
"  document.getElementById('btn-remeasure').style.display='none';"
"  document.getElementById('meas-result').innerHTML='<div style=\"color:#8b949e;font-size:13px\">Ready to measure</div>';"
"  await fetch('/api/record/delete',{method:'POST',"
"    headers:{'Content-Type':'application/json'},"
"    body:JSON.stringify({index:idx})});"
"  var m=(settings&&settings.obs_method!==undefined)?settings.obs_method:0;"
"  if(m===0||m===4){"
"    setSightUI(sight);"
"    if(m===0&&sight==='FS')showFsNameField();"
"    else hideFsNameField();"
"  }else if(m>=1&&m<=3){"
"    var st=await fetch('/api/status');"
"    var sd=await st.json();"
"    s_dblr_step=sd.dblr_step||1;"
"    if(s_dblr_step===2)showFsNameField();"
"    else hideFsNameField();"
"  }"
"  await refreshStatus();"
"  loadRecords();"
"}"

// ── Insert / Re-measure setup ──
"async function cancelInsert(){"
"  await fetch('/api/insert_cancel',{method:'POST'});"
"  await refreshStatus();"
"  showToast('Insert mode cancelled');"
"}"
"async function reMeasureSetup(vsn,storedSetupNo,afterIdx){"
"  showConfirm('Re-measure setup '+vsn+'? Its '+4+' records will be deleted and you re-take them.',async function(){"
"    var resp=await fetch('/api/remeasure_setup',{method:'POST',"
"      headers:{'Content-Type':'application/json'},"
"      body:JSON.stringify({setup_no:storedSetupNo,after_index:afterIdx})});"
"    if(resp.ok){"
"      await loadRecords();"
"      await refreshStatus();"
"      showTab(0);"
"      showToast('Setup '+vsn+' deleted — take new BS1');"
"    }"
"  });"
"}"

// ── Records ──
"async function loadRecords(){"
"  try{"
"    var r=await fetch('/api/records');"
"    var d=await r.json();"
"    var tb=document.getElementById('rec-tbody');"
"    if(!d.records||!d.records.length){"
"      tb.innerHTML='<tr><td colspan=\"9\" style=\"text-align:center;color:#8b949e;padding:20px\">No records</td></tr>';"
"      updateSummary([]);return;"
"    }"
"    var setupColors=['#58a6ff','#3fb950','#bc8cff','#ff9900','#ff6b6b','#00d4aa','#ffd700','#ff85c2','#a5d6ff','#b5f7a0'];"
"    var sn=0,lastWasFS=true,setupMap={};"
"    d.records.forEach(function(r){"
"      if(r.sight==='BS'||r.sight==='BS1'){sn++;lastWasFS=false;setupMap[r.index]=sn;}"
"      else if(r.sight==='FS'){setupMap[r.index]=lastWasFS?0:sn;lastWasFS=true;}"
"      else if(r.sight==='FS1'||r.sight==='FS2'||r.sight==='BS2'){setupMap[r.index]=sn;}"
"      else{setupMap[r.index]=sn;}"
"    });"
"    var lastIdxBySn={};"
"    d.records.forEach(function(r){var s=setupMap[r.index]||0;if(s>0)lastIdxBySn[s]=r.index;});"
"    var _hi=0,_rl=0,_bmSet=false;"
"    d.records.forEach(function(r){"
"      if(!_bmSet){_rl=r.rl;_bmSet=true;}"
"      if(r.sight==='BS'){_hi=_rl+r.staff;r.hi=_hi;}"
"      else if(r.sight==='IS'||r.sight==='FS'){r.hi=_hi;r.rl=_hi-r.staff;_rl=r.rl;}"
"    });"
"    tb.innerHTML=d.records.map(function(r){"
"      var s=setupMap[r.index]||0;"
"      var col=s>0?setupColors[(s-1)%10]:'#666666';"
"      var orphan=(r.sight==='FS'&&s===0);"
"      var isSetupStart=(r.sight==='BS'||r.sight==='BS1');"
"      var prevLastIdx=isSetupStart?(lastIdxBySn[s-1]||0):0;"
"      var stnCell=isSetupStart&&s>0"
"        ?'<td class=\"setup-num\">'+s+'<button class=\"btn-sm\" onclick=\"reMeasureSetup('+s+','+r.setup_no+','+prevLastIdx+')\" style=\"padding:1px 5px;font-size:10px;margin-left:4px\">&#x21BA;</button></td>'"
"        :'<td>'+(s>0?s:'')+'</td>';"
"      return '<tr style=\"color:'+col+'\">'"
"        +'<td>'+r.index+'</td>'"
"        +stnCell"
"        +'<td style=\"cursor:pointer;text-decoration:underline\" onclick=\"editName('+r.index+',\\''+(r.name||'')+'\\')\">'"
"            +(r.name||'---')+'</td>'"
"        +'<td>'+(orphan?'(!)':'')+r.sight+'</td>'"
"        +'<td>'+r.staff.toFixed(4)+'</td>'"
"        +'<td>'+r.distance.toFixed(3)+'</td>'"
"        +'<td>'+r.hi.toFixed(4)+'</td>'"
"        +'<td>'+r.rl.toFixed(4)+'</td>'"
"        +'<td style=\"text-align:center\">'+(r.note?"
"            '<span class=\"note-dot\" onclick=\"editNote('+r.index+',\\''+(r.name||'')+'\\',\\''+(r.sight||'')+'\\','+r.setup_no+')\">&#x25CF;</span>'"
"            :'<span style=\"color:#444;font-size:12px;cursor:pointer\" onclick=\"editNote('+r.index+',\\''+(r.name||'')+'\\',\\''+(r.sight||'')+'\\','+r.setup_no+')\">+</span>'"
"          )+'</td>'"
"        +'<td><button class=\"btn-sm btn-danger\" onclick=\"delRec('+r.index+','+s+')\">'+String.fromCharCode(10005)+'</button></td>'"
"        +'</tr>';"
"    }).join('');"
"    cachedRecords=d.records;"
"    updateSummary(d.records);"
"  }catch(e){}"
"}"
"function updateSummary(recs){"
"  var ids=['rc-sbs','rc-sfs','rc-diff','rc-frl','rc-arl','rc-stn','rc-stn-lbl','rc-chk',"
"           'rd-sbs','rd-sfs','rd-diff','rd-lim','rd-stat'];"
"  if(!recs||!recs.length){"
"    ids.forEach(function(id){var el=document.getElementById(id);if(el)el.textContent=id==='rc-stn-lbl'?'BS-FS':'---';});return;"
"  }"
"  var sumBFbs=0,sumBFfs=0,sumBFbsd=0,sumBFfsd=0;"
"  var setups=[],cur=null;"
"  var firstRL=null,lastRL=null,lastHI=null,lastSight=null;"
"  recs.forEach(function(r){"
"    if(r.rl!==undefined){if(firstRL===null)firstRL=r.rl;lastRL=r.rl;}"
"    if(r.hi!==undefined)lastHI=r.hi;"
"    lastSight=r.sight;"
"    if(r.sight==='BS'){sumBFbs+=r.staff;sumBFbsd+=r.distance;}"
"    else if(r.sight==='FS'){sumBFfs+=r.staff;sumBFfsd+=r.distance;}"
"    else if(r.sight==='BS1'){cur={bs1:r.staff,bs1d:r.distance};}"
"    else if(r.sight==='FS1'&&cur){cur.fs1=r.staff;cur.fs1d=r.distance;}"
"    else if(r.sight==='FS2'&&cur&&cur.fs1!==undefined){cur.fs2=r.staff;cur.fs2d=r.distance;}"
"    else if(r.sight==='BS2'&&cur&&cur.fs2!==undefined){cur.bs2=r.staff;cur.bs2d=r.distance;setups.push(cur);cur=null;}"
"  });"
"  var sumBFFBbs=0,sumBFFBfs=0,sumBFFBbsd=0,sumBFFBfsd=0;"
"  setups.forEach(function(s){"
"    sumBFFBbs+=(s.bs1+s.bs2)/2;"
"    sumBFFBfs+=(s.fs1+s.fs2)/2;"
"    sumBFFBbsd+=(s.bs1d+s.bs2d)/2;"
"    sumBFFBfsd+=(s.fs1d+s.fs2d)/2;"
"  });"
"  var totalBS=sumBFbs+sumBFFBbs;"
"  var totalFS=sumBFfs+sumBFFBfs;"
"  var totalBSd=sumBFbsd+sumBFFBbsd;"
"  var totalFSd=sumBFfsd+sumBFFBfsd;"
"  var diff=totalBS-totalFS;"
"  var hasFS=(sumBFfs>0||setups.length>0||cur&&cur.fs1!==undefined);"
"  if(setups.length===0&&cur){if(cur.bs1!==undefined){sumBFFBbs=cur.bs1;sumBFFBbsd=cur.bs1d;}if(cur.fs1!==undefined){sumBFFBfs=cur.fs1;sumBFFBfsd=cur.fs1d;}totalBS=sumBFbs+sumBFFBbs;totalFS=sumBFfs+sumBFFBfs;totalBSd=sumBFbsd+sumBFFBbsd;totalFSd=sumBFfsd+sumBFFBfsd;diff=totalBS-totalFS;}"
"  var calcLast=firstRL!==null?firstRL+diff:null;"
"  var lastCmpSetup=setups.length>0?setups[setups.length-1]:null;"
"  var arithOk=lastCmpSetup?Math.abs((lastCmpSetup.bs1-lastCmpSetup.fs1)-(lastCmpSetup.bs2-lastCmpSetup.fs2))<=(settings.max_station_mm||2.0)/1000:(calcLast!==null&&lastRL!==null&&Math.abs(calcLast-lastRL)<0.001);"
"  document.getElementById('rc-sbs').textContent=totalBS.toFixed(4)+'m';"
"  document.getElementById('rc-sfs').textContent=hasFS?totalFS.toFixed(4)+'m':'---';"
"  document.getElementById('rc-diff').textContent=hasFS?((diff>=0?'+':'')+diff.toFixed(4)+'m'):'---';"
"  document.getElementById('rc-frl').textContent=firstRL!==null?firstRL.toFixed(4)+'m':'---';"
"  var isComplete=lastSight==='FS'||setups.length>0;"
"  document.getElementById('rc-arl-lbl').textContent=isComplete?'Last RL':'Last HI';"
"  document.getElementById('rc-arl').textContent=isComplete?(lastRL!==null?lastRL.toFixed(4)+'m':'---'):(lastHI?lastHI.toFixed(4)+'m':'---');"
"  var stnEl=document.getElementById('rc-stn');"
"  var stnLblEl=document.getElementById('rc-stn-lbl');"
"  if(stnLblEl)stnLblEl.textContent='BS-FS';"
"  if(lastCmpSetup){"
"    var stnDiff=(lastCmpSetup.bs1+lastCmpSetup.bs2)/2-(lastCmpSetup.fs1+lastCmpSetup.fs2)/2;"
"    if(stnEl)stnEl.textContent=(stnDiff>=0?'+':'')+stnDiff.toFixed(4)+'m';"
"  }else if(cur&&cur.bs1!==undefined&&cur.fs1!==undefined){"
"    var stnDiff=cur.bs1-cur.fs1;"
"    if(stnEl)stnEl.textContent=(stnDiff>=0?'+':'')+stnDiff.toFixed(4)+'m';"
"  }else{if(stnEl)stnEl.textContent='---';}"
"  var method=settings.obs_method||0;"
"  var chkEl=document.getElementById('rc-chk');"
"  if(method===0){chkEl.textContent='';}"
"  else if(!isComplete){chkEl.innerHTML='<span style=\"color:#8b949e;font-size:12px\">In progress...</span>';}"
"  else{chkEl.innerHTML=arithOk?'<span class=\"ok\">PASS</span>':'<span class=\"err\">FAIL</span>';}"
"  var distDiff=Math.abs(totalBSd-totalFSd),lim=settings.max_cum_diff||10.0;"
"  document.getElementById('rd-sbs').textContent=totalBSd.toFixed(3)+'m';"
"  document.getElementById('rd-sfs').textContent=totalFSd.toFixed(3)+'m';"
"  document.getElementById('rd-diff').textContent=distDiff.toFixed(3)+'m';"
"  document.getElementById('rd-lim').textContent=lim.toFixed(1)+'m';"
"  document.getElementById('rd-stat').innerHTML=distDiff<=lim?'<span class=\"ok\">PASS</span>':'<span class=\"err\">FAIL</span>';"
"}"
"async function editName(idx,curName){"
"  var newName=prompt('Point name (max 23 chars):',curName||'');"
"  if(newName===null)return;"
"  newName=newName.substring(0,23).trim();"
"  if(!newName){showToast('Name cannot be empty');return;}"
"  var resp=await fetch('/api/record/name',{method:'POST',"
"    headers:{'Content-Type':'application/json'},"
"    body:JSON.stringify({index:idx,name:newName})});"
"  if(resp.ok){showToast('Name updated: '+newName);loadRecords();}"
"  else{showToast('Error updating name');}"
"}"
"async function delRec(idx,setupNum){"
"  var recs=cachedRecords;"
"  var rec=recs.find(function(r){return r.index===idx;});"
"  if(!rec)return;"
"  var warning='';"
"  if(rec.sight==='BS'){"
"    var nextFS=null;"
"    for(var i=0;i<recs.length;i++){"
"      if(recs[i].index===idx){"
"        for(var j=i+1;j<recs.length;j++){"
"          if(recs[j].sight==='BS')break;"
"          if(recs[j].sight==='FS'){nextFS=recs[j];break;}"
"        }"
"        break;"
"      }"
"    }"
"    if(nextFS)warning='BS#'+idx+' delete will orphan FS#'+nextFS.index+'. Continue?';"
"    else warning='Delete BS#'+idx+'?';"
"  }else if(rec.sight==='FS'){"
"    var prevBS=null;"
"    for(var i=0;i<recs.length;i++){"
"      if(recs[i].index===idx){"
"        for(var j=i-1;j>=0;j--){"
"          if(recs[j].sight==='FS')break;"
"          if(recs[j].sight==='BS'){prevBS=recs[j];break;}"
"        }"
"        break;"
"      }"
"    }"
"    if(prevBS)warning='FS#'+idx+' delete will unbalance BS#'+prevBS.index+'. Continue?';"
"    else warning='Delete orphan FS#'+idx+'?';"
"  }else{"
"    warning='Delete IS#'+idx+'?';"
"  }"
"  showConfirm(warning,async function(){"
"    await fetch('/api/record/delete',{method:'POST',"
"      headers:{'Content-Type':'application/json'},"
"      body:JSON.stringify({index:idx})});"
"    loadRecords();refreshStatus();"
"  });"
"  return;"
"}"


// ── Jobs ──
"async function loadFiles(){"
"  try{"
"    var r=await fetch('/api/files');"
"    var d=await r.json();"
"    var el=document.getElementById('file-list');"
"    el.innerHTML=d.files.map(function(f){"
"      return '<div style=\"padding:2px 0;border-bottom:1px solid #21262d\">'"
"        +f.name+' <span style=\"color:#8b949e\">'+f.size+'B</span></div>';"
"    }).join('');"
"  }catch(e){showToast('Error: '+e);}"
"}"
"async function loadJobs(){"
"  try{"
"    var r=await fetch('/api/jobs');"
"    var d=await r.json();"
"    var el=document.getElementById('job-list');"
"    if(!d.jobs||!d.jobs.length){"
"      el.innerHTML='<div style=\"color:#8b949e;text-align:center;padding:12px\">No jobs</div>';"
"      return;"
"    }"
"    window._jobNames=d.jobs.map(function(j){return j.name;});"
"    d.jobs.sort(function(a,b){"
"      if(a.name===d.active)return -1;"
"      if(b.name===d.active)return 1;"
"      return a.name.localeCompare(b.name);"
"    });"
"    el.innerHTML=d.jobs.map(function(j){"
"      var isActive=j.name===d.active;"
"      return '<div style=\"padding:8px 0;border-bottom:1px solid #21262d;display:flex;justify-content:space-between;align-items:center\">'+"
"        '<div>'+"
"          '<div style=\"font-size:14px;color:'+(isActive?'#39d5ff':'#e6edf3')+'\">'+(isActive?'>':'')+j.name+'</div>'+"
"          '<div style=\"font-size:11px;color:#8b949e\">BM:'+j.bench_rl.toFixed(4)+'m . '+j.points+' pts . '+Math.round(j.size/1024*10)/10+'KB</div>'+"
"        '</div>'+"
"        '<div style=\"display:flex;gap:4px\">'+"
"          (!isActive?'<button class=\"btn-sm\" onclick=\"selectJob(this.dataset.name)\" data-name=\"'+j.name+'\">Select</button>':'')+"
"          '<button class=\"btn-sm btn-danger\" onclick=\"deleteJob(this.dataset.name)\" data-name=\"'+j.name+'\">x</button>'+"
"        '</div>'+"
"      '</div>';"
"    }).join('');"
"  }catch(e){}"
"}"
"async function newJob(){"
"  var name=document.getElementById('new-job-name').value.trim();"
"  var bmInput=document.getElementById('new-job-bm').value;"
"  var bm=bmInput?parseFloat(bmInput):parseFloat(document.getElementById('j-bm').textContent)||100.0;"
"  if(!name){showToast('Enter job name');return;}"
"  if(isNaN(bm)){showToast('Enter benchmark RL');return;}"
"  var existingJobs=document.querySelectorAll('#job-list div');"
"  var jobs=[];"
"  if(window._jobNames&&window._jobNames.indexOf(name)>=0){"
"    showToast('Job '+name+' already exists!');return;}"
"  var curJob=document.getElementById('j-name').textContent||'current job';"
"  var curPts=document.getElementById('j-pts').textContent||'0';"
"  var msg='Create new job: '+name+'?';"
"  msg+=' Current job ['+curJob+'] ('+curPts+' points) will be saved.';"
"  showConfirm(msg,async function(){"
"    await fetch('/api/job/new',{method:'POST',"
"      headers:{'Content-Type':'application/json'},"
"      body:JSON.stringify({name:name,bench_rl:bm})});"
"    document.getElementById('new-job-name').value='';"
"    document.getElementById('new-job-bm').value='';"
"    await loadJobs();await refreshStatus();setSightUI('BS');loadRecords();clearReport();var mr=document.getElementById('meas-result');if(mr)mr.textContent='';"
"    showToast('Job created: '+name+' - tap Measure to start');"
"    showTab(0);"
"  });"
"  return;"
"}"

"async function selectJob(name){"
"  showConfirm('Switch to job: '+name+'?',async function(){"
"    await fetch('/api/job/select',{method:'POST',"
"      headers:{'Content-Type':'application/json'},"
"      body:JSON.stringify({name:name})});"
"    loadJobs();refreshStatus();loadRecords();clearReport();"
"    showTab(0);showToast('Switched to: '+name);"
"  });"
"}"
"async function deleteJob(name){"
"  showConfirm('Delete job: '+name+'? This cannot be undone.',async function(){"
"    await fetch('/api/job/delete',{method:'POST',"
"      headers:{'Content-Type':'application/json'},"
"      body:JSON.stringify({name:name})});"
"    loadJobs();refreshStatus();showToast('Deleted: '+name);"
"  });"
"}"
"async function setBench(){"
"  var bm=parseFloat(document.getElementById('new-bm').value);"
"  if(isNaN(bm)){showToast('Enter a valid RL value');return;}"
"  await fetch('/api/job/bench',{method:'POST',"
"    headers:{'Content-Type':'application/json'},"
"    body:JSON.stringify({bench_rl:bm})});"
"  refreshStatus();showToast('Benchmark RL set to '+bm.toFixed(4)+'m');"
"}"
"function editNote(idx,name,sight,setup_no){"
"  var cur='';"
"  fetch('/api/note?name='+encodeURIComponent(name)+'&sight='+encodeURIComponent(sight)+'&setup='+setup_no)"
"  .then(function(r){return r.json();})"
"  .then(function(d){"
"    cur=d.note||'';"
"    var v=prompt('Note for '+name+' '+sight+' (max 27 chars):',cur);"
"    if(v===null)return;"
"    v=v.substring(0,27);"
"    fetch('/api/note',{method:'POST',headers:{'Content-Type':'application/json'},"
"      body:JSON.stringify({name:name,sight:sight,setup_no:setup_no,note:v})})"
"    .then(function(){loadRecords();});"
"  });"
"}"
"function downloadCSV(){"
"  var a=document.createElement('a');"
"  a.href='/api/download';"
"  a.download='';"
"  document.body.appendChild(a);a.click();document.body.removeChild(a);"
"}"
"function downloadM5(){"
"  var a=document.createElement('a');"
"  a.href='/api/download/m5';"
"  a.download='';"
"  document.body.appendChild(a);a.click();document.body.removeChild(a);"
"}"
"function downloadReportCSV(){"
"  if(!cachedReport){showToast('Run Calculate Misclosure first');return;}"
"  var r=cachedReport,recs=cachedRecords;"
"  var methods=['BF','BFFB','BFBF','BBFF','SET-OUT'];"
"  var mc=r.misclose,absMC=Math.abs(mc)*1000;"
"  var diffCum=Math.abs(r.sumBSDist-r.sumFSDist);"
"  var lim=settings.max_cum_diff||10.0;"
"  var rows=["
"    'SDL30 Leveling Report',"
"    'Job:,'+r.job,"
"    'Date:,'+r.date,"
"    'Opening BM RL (m):,'+r.openBM.toFixed(4),"
"    'Closing BM RL (m):,'+r.closeBM.toFixed(4),"
"    'Method:,'+(methods[r.method]||'BF'),"
"    '','ARITHMETIC CHECK',"
"    'Sum BS (m):,'+(r.sumBS>=0?'+':'')+r.sumBS.toFixed(4),"
"    'Sum FS (m):,'+(r.sumFS>=0?'+':'')+r.sumFS.toFixed(4),"
"    'Delta Elev (m):,'+(r.dh>=0?'+':'')+r.dh.toFixed(4),"
"    'Computed Elev (m):,'+r.compElev.toFixed(4),"
"    'Closing BM (m):,'+r.closeBM.toFixed(4),"
"    'Misclosure (m):,'+(mc>=0?'+':'')+mc.toFixed(4),"
"    'Misclosure (mm):,'+(mc>=0?'+':'')+absMC.toFixed(1),"
"    'Points:,'+r.points,'Readings:,'+r.readings,"
"    '','DISTANCE BALANCE',"
"    'Sum BS Dist (m):,'+r.sumBSDist.toFixed(3),"
"    'Sum FS Dist (m):,'+r.sumFSDist.toFixed(3),"
"    'Dist Balance (m):,'+diffCum.toFixed(3)+'('+(diffCum<=lim?'PASS':'FAIL')+')',"
"    'Total Dist (m):,'+(r.sumBSDist+r.sumFSDist).toFixed(3),"
"    '','OBSERVATION RECORDS',"
"    'Point,Setup,Name,Sight,Staff (m),Dist (m),HI (m),RL (m),Note'"
"  ];"
"  recs.forEach(function(rec){"
"    rows.push([rec.index,rec.setup_no,rec.name,rec.sight,"
"      rec.staff.toFixed(4),rec.distance.toFixed(3),"
"      rec.hi.toFixed(4),rec.rl.toFixed(4),"
"      (rec.note||'').replace(/,/g,';')].join(','));"
"  });"
"  var blob=new Blob([rows.join('\\r\\n')],{type:'text/csv'});"
"  var url=URL.createObjectURL(blob);"
"  var a=document.createElement('a');"
"  a.href=url;a.download=r.job+'_report.csv';"
"  document.body.appendChild(a);a.click();document.body.removeChild(a);"
"  URL.revokeObjectURL(url);"
"}"
"function downloadReportHTML(){"
"  if(!cachedReport){showToast('Run Calculate Misclosure first');return;}"
"  var r=cachedReport,recs=cachedRecords;"
"  var methods=['BF','BFFB','BFBF','BBFF','SET-OUT'];"
"  var mc=r.misclose,absMC=Math.abs(mc)*1000;"
"  var diffCum=Math.abs(r.sumBSDist-r.sumFSDist);"
"  var lim=settings.max_cum_diff||10.0;"
"  var mcCls=absMC<5?'ok':absMC<20?'warn':'err';"
"  var dcCls=diffCum<=lim?'ok':'err';"
"  var sColors=['#dce9f7','#d9f0dc','#ece2f5','#fdecd0','#fde0e0',"
"    '#cffaf5','#fef9d0','#fde0f0','#e0ecff','#e5fdd1'];"
"  function ir(l,v){return '<tr><td>'+l+'</td><td>'+v+'</td></tr>';}"
"  var _ci=-1;"
"  var recRows=recs.map(function(rec){"
"    if(rec.sight==='BS'||rec.sight==='BS1')_ci++;"
"    var bg=_ci>=0?sColors[_ci%10]:'#f5f5f5';"
"    return '<tr style=\"background:'+bg+'\">'+"
"      '<td>'+rec.index+'</td><td>'+rec.setup_no+'</td><td>'+(rec.name||'')+'</td>'+"
"      '<td>'+rec.sight+'</td><td>'+rec.staff.toFixed(4)+'</td><td>'+rec.distance.toFixed(3)+'</td>'+"
"      '<td>'+rec.hi.toFixed(4)+'</td><td>'+rec.rl.toFixed(4)+'</td>'+"
"      '<td>'+(rec.note||'')+'</td></tr>';"
"  }).join('');"
"  var css='body{font-family:Arial,sans-serif;font-size:12px;margin:20px;color:#000}'"
"    +'h1{font-size:18px;margin-bottom:4px}'"
"    +'h2{font-size:13px;margin:16px 0 4px;border-bottom:1px solid #999;padding-bottom:2px}'"
"    +'table{border-collapse:collapse;margin-top:4px}'"
"    +'.it{width:360px}.it td{padding:3px 8px;border:1px solid #ccc}'"
"    +'.it td:first-child{font-weight:bold;width:160px}'"
"    +'.rt{width:100%}.rt th{background:#333;color:#fff;padding:4px 6px;text-align:left;font-size:11px}'"
"    +'.rt td{padding:3px 6px;border:1px solid #ccc;font-size:11px}'"
"    +'.ok{color:green;font-weight:bold}.warn{color:#b8860b;font-weight:bold}.err{color:red;font-weight:bold}';"
"  var html='<!DOCTYPE html><html><head><meta charset=\"utf-8\">'"
"    +'<title>SDL30 Report - '+r.job+'</title>'"
"    +'<style>'+css+'</style></head><body>'"
"    +'<h1>SDL30 Leveling Report</h1>'"
"    +'<p style=\"color:#555;margin:0 0 12px\">'+r.date+'</p>'"
"    +'<table class=\"it\">'"
"    +ir('Job',r.job)"
"    +ir('Opening BM RL',r.openBM.toFixed(4)+' m')"
"    +ir('Closing BM RL',r.closeBM.toFixed(4)+' m')"
"    +ir('Method',methods[r.method]||'BF')"
"    +'</table>'"
"    +'<h2>Arithmetic Check</h2><table class=\"it\">'"
"    +ir('&Sigma; BS',(r.sumBS>=0?'+':'')+r.sumBS.toFixed(4)+' m')"
"    +ir('&Sigma; FS',(r.sumFS>=0?'+':'')+r.sumFS.toFixed(4)+' m')"
"    +ir('&Delta;Elev',(r.dh>=0?'+':'')+r.dh.toFixed(4)+' m')"
"    +ir('Computed Elev',r.compElev.toFixed(4)+' m')"
"    +ir('Closing BM',r.closeBM.toFixed(4)+' m')"
"    +ir('Misclosure','<span class=\"'+mcCls+'\">'+(mc>=0?'+':'')+mc.toFixed(4)+' m ('+(mc>=0?'+':'')+absMC.toFixed(1)+' mm)</span>')"
"    +ir('Points',r.points)+ir('Readings',r.readings)"
"    +'</table>'"
"    +'<h2>Distance Balance</h2><table class=\"it\">'"
"    +ir('&Sigma; BS dist',r.sumBSDist.toFixed(3)+' m')"
"    +ir('&Sigma; FS dist',r.sumFSDist.toFixed(3)+' m')"
"    +ir('Dist Balance','<span class=\"'+dcCls+'\">'+diffCum.toFixed(3)+' m ('+(diffCum<=lim?'PASS':'FAIL')+')</span>')"
"    +ir('Total dist',(r.sumBSDist+r.sumFSDist).toFixed(3)+' m')"
"    +'</table>'"
"    +'<h2>Observation Records</h2><table class=\"rt\">'"
"    +'<tr><th>Pt#</th><th>Setup</th><th>Name</th><th>Sight</th>"
"<th>Staff (m)</th><th>Dist (m)</th><th>HI (m)</th><th>RL (m)</th><th>Note</th></tr>'"
"    +recRows+'</table></body></html>';"
"  var blob=new Blob([html],{type:'text/html'});"
"  var url=URL.createObjectURL(blob);"
"  var a=document.createElement('a');"
"  a.href=url;a.download=r.job+'_report.html';"
"  document.body.appendChild(a);a.click();document.body.removeChild(a);"
"  URL.revokeObjectURL(url);"
"}"

// ── Misclose ──
"function clearReport(){"
"  document.getElementById('report-card').style.display='none';"
"  document.getElementById('dist-card').style.display='none';"
"  document.getElementById('closing-rl').value='';"
"  cachedReport=null;"
"  ['rpt-bs','rpt-fs','rpt-dh','rpt-chk','rpt-cel','rpt-mc','rpt-pts','rpt-rdg',"
"   'rpt-bsd','rpt-fsd','rpt-dcd','rpt-td'].forEach(function(id){"
"    var el=document.getElementById(id);if(el)el.textContent='---';"
"  });"
"}"
"function updateDblrCard(d,m){"
"  var mi=m-1,lbl=DBLR_LABELS[mi],step=d.dblr_step;"
"  var dm=document.getElementById('dblr-method');if(dm)dm.textContent=DBLR_METHODS[mi];"
"  var done=step>=5?4:step-1;"
"  var nl=step>0&&step<=4?lbl[step-1]:'BS1';"
"  document.getElementById('dblr-step-lbl').textContent=step>=5?(d.passed?'PASS':'FAIL'):'Step '+step+'/4: '+nl;"
"  for(var i=1;i<=4;i++){var b=document.getElementById('ds'+i);"
"    b.style.background=i<=done?'#3fb950':i===step&&step<=4?'#58a6ff':'#21262d';}"
"  var re=document.getElementById('dblr-readings');"
"  if(re){"
"    re.innerHTML='';"
"    var vals2=[d.bs1,d.fs1,d.fs2,d.bs2];"
"    var done2=step>=5?4:step-1;"
"    for(var ri=0;ri<4;ri++){"
"      var sp=document.createElement('span');"
"      sp.style.flex='1';sp.style.textAlign='center';"
"      sp.style.color=ri<done2?'#3fb950':'#8b949e';"
"      sp.textContent=lbl[ri]+':'+(ri<done2&&vals2[ri]?vals2[ri].toFixed(4):'---');"
"      re.appendChild(sp);"
"    }}"
"  var res=document.getElementById('dblr-result'),rb=document.getElementById('dblr-repeat-btn');"
"  if(step>=5){"
"    res.style.display='block';"
"    if(d.passed){res.style.background='#0d2818';res.style.color='#3fb950';res.style.border='1px solid #238636';"
"      res.textContent='PASS diff:'+d.diff_mm.toFixed(3)+'mm BS:'+((d.bs1+d.bs2)/2).toFixed(4)+' FS:'+((d.fs1+d.fs2)/2).toFixed(4);"
"      rb.style.display='none';refreshStatus();loadRecords();"
"      setTimeout(function(){res.style.display='none';},3000);"
"    }else{res.style.background='#3d1c1c';res.style.color='#f85149';res.style.border='1px solid #6e2424';"
"      res.textContent='FAIL diff:'+d.diff_mm.toFixed(3)+'mm > '+settings.max_station_mm+'mm';"
"      rb.style.display='block';}}"
"  else{res.style.display='none';rb.style.display='none';}"
"}"
"async function clearSetup(){"
"  showConfirm('Clear current setup? This will delete unsaved readings.',async function(){"
"  try{"
"    for(var i=0;i<10;i++){"
"      var rd=await fetch('/api/records');"
"      var dd=await rd.json();"
"      if(!dd.records||dd.records.length===0)break;"
"      var last=dd.records[dd.records.length-1];"
"      if(last.sight==='BS2'||last.sight==='FS')break;"
"      await fetch('/api/record/delete',{method:'POST',"
"        headers:{'Content-Type':'application/json'},"
"        body:JSON.stringify({index:last.index})});"
"      if(last.sight==='BS1')break;"
"    }"
"    await fetch('/api/dblr_repeat',{method:'POST'});"
"  }catch(e){showToast('Error: '+e);return;}"
"  document.getElementById('meas-result').innerHTML='<span style=\"color:#8b949e\">Ready to measure</span>';"
"  var re=document.getElementById('dblr-readings');"
"  if(re)re.innerHTML='';"
"  for(var i=1;i<=4;i++){var b=document.getElementById('ds'+i);if(b)b.style.background='#21262d';}"
"  await loadRecords();"
"  await refreshStatus();"
"  showToast('Setup cleared');"
"  });" 
"}"
"async function dblrRepeat(){"
"  await fetch('/api/dblr_repeat',{method:'POST'});"
"  document.getElementById('dblr-result').style.display='none';"
"  document.getElementById('dblr-repeat-btn').style.display='none';"
"  document.getElementById('dblr-readings').textContent='';"
"  for(var i=1;i<=4;i++)document.getElementById('ds'+i).style.background='#21262d';"
"  var dsl=document.getElementById('dblr-step-lbl');if(dsl)dsl.textContent='Step 1/4';"
"  showToast('Setup cleared - start BS1');"
"}"
"async function calcMisclose(){"
"  var crl=parseFloat(document.getElementById('closing-rl').value);"
"  if(isNaN(crl)){showToast('Enter closing benchmark RL');return;}"
"  try{"
"    var r=await fetch('/api/misclose?closing_rl='+crl);"
"    var d=await r.json();"
"    document.getElementById('report-card').style.display='block';"
"    document.getElementById('dist-card').style.display='block';"
"    var mc=d.misclose,absMC=Math.abs(mc)*1000;"
"    var cls=absMC<5?'misclose-ok':absMC<20?'misclose-warn':'misclose-err';"
"    var compElevVal=d.comp_elev||(d.opening_bm+d.sum_bs-d.sum_fs);"
"    var obsDH=compElevVal-d.opening_bm;"
"    document.getElementById('rpt-bs').textContent=(d.sum_bs>=0?'+':'')+d.sum_bs.toFixed(4)+'m';"
"    document.getElementById('rpt-fs').textContent=(d.sum_fs>=0?'+':'')+d.sum_fs.toFixed(4)+'m';"
"    document.getElementById('rpt-dh').textContent=(obsDH>=0?'+':'')+obsDH.toFixed(4)+'m';"
"    document.getElementById('rpt-chk').textContent=compElevVal.toFixed(4)+'m';"
"    document.getElementById('rpt-cel').textContent=crl.toFixed(4)+'m';"
"    document.getElementById('rpt-mc').innerHTML='<span class=\"'+cls+'\">'+(mc>=0?'+':'')+mc.toFixed(4)+'m ('+absMC.toFixed(1)+'mm)</span>';"
"    document.getElementById('rpt-pts').textContent=d.points;"
"    document.getElementById('rpt-rdg').textContent=d.readings||d.points;"
"    var lim=parseFloat(document.getElementById('s-maxcd').value)||10.0;"
"    var diffCum=Math.abs(d.sum_bs_dist-d.sum_fs_dist);"
"    var dcOk=diffCum<=lim;"
"    document.getElementById('rpt-bsd').textContent=(d.sum_bs_dist||0).toFixed(3)+'m';"
"    document.getElementById('rpt-fsd').textContent=(d.sum_fs_dist||0).toFixed(3)+'m';"
"    var lim2=settings.max_cum_diff||10.0;"
"    document.getElementById('rpt-dcd').innerHTML=diffCum.toFixed(3)+'m'"
"      +' <span style=\"color:'+(dcOk?'#3fb950':'#f85149')+'\">'+(dcOk?'< OK':'> FAIL')+'</span>';"
"    document.getElementById('rpt-td').textContent=(d.sum_bs_dist+d.sum_fs_dist).toFixed(3)+'m';"
"    cachedReport={job:document.getElementById('j-name').textContent,"
"      date:new Date().toISOString().slice(0,10),"
"      openBM:d.opening_bm,closeBM:crl,method:settings.obs_method||0,"
"      sumBS:d.sum_bs,sumFS:d.sum_fs,dh:compElevVal-d.opening_bm,"
"      compElev:compElevVal,"
"      misclose:d.misclose,points:d.points,readings:d.readings||d.points,"
"      sumBSDist:d.sum_bs_dist||0,sumFSDist:d.sum_fs_dist||0};"
"    await loadRecords();"
"  }catch(e){showToast('Error: '+e);}"
"}"

// ── Settings ──
"async function loadSettings(){"
"  try{"
"    var r=await fetch('/api/settings');"
"    var d=await r.json();"
"    settings=d;"
"    document.getElementById('s-maxst').value=d.max_station_mm||2.0;"
"    document.getElementById('s-maxdd').value=d.max_dist_diff||5.0;"
"    document.getElementById('s-maxcd').value=d.max_cum_diff||10.0;"
"    document.getElementById('s-minsh').value=d.min_sight_ht||0.3;"
"    document.getElementById('s-maxsd').value=d.max_sight_dist||50;"
"    document.getElementById('s-alert').checked=d.alert_on_exceed!==false;"
"    document.getElementById('s-block').checked=d.block_on_exceed===true;"
"    document.getElementById('s-baud').value=d.baud_rate||2400;"
"    setMethodUI(d.obs_method||0);"
"  }catch(e){}"
"}"
"function setMethodUI(m){"
"  for(var i=0;i<5;i++){var mb=document.getElementById('mb-'+i);if(mb)mb.classList.toggle('active',i===m);}"
"  var isSetout=(m===4);"
"  var isDblr=(m>=1&&m<=3);"
"  document.getElementById('sight-leveling').style.display=(isSetout||isDblr)?'none':'grid';"
"  var ds2=document.getElementById('dblr-steps');"
"  if(ds2)ds2.style.display=isDblr?'block':'none';"
"  document.getElementById('sight-setout').style.display=isSetout?'grid':'none';"
"  document.getElementById('setout-fields').style.display=isSetout?'block':'none';"
"  document.getElementById('sight-card-title').textContent=isSetout?'Set-out':'Sight type';"
"  var mb=document.getElementById('method-badge');"
"  var methods=['BF','BFFB','BFFB','BFFB','SET-OUT'];"
"  if(mb)mb.textContent=methods[m]||'BF';"
"  if(isSetout){setSightUI('BS');}else{setSightUI('BS');}"
"}"
"function setMethod(m){"
"  setMethodUI(m);"
"  if(!settings)settings={};"
"  settings.obs_method=m;"
"  saveSettings();"
"}"
"async function saveSettings(){"
"  var s={"
"    obs_method:parseInt(document.querySelector('[id^=mb-].active').id.replace('mb-','')),"
"    max_station_mm:parseFloat(document.getElementById('s-maxst').value),"
"    max_dist_diff:parseFloat(document.getElementById('s-maxdd').value),"
"    max_cum_diff:parseFloat(document.getElementById('s-maxcd').value),"
"    min_sight_ht:parseFloat(document.getElementById('s-minsh').value),"
"    max_sight_dist:parseFloat(document.getElementById('s-maxsd').value),"
"    alert_on_exceed:document.getElementById('s-alert').checked,"
"    block_on_exceed:document.getElementById('s-block').checked,"
"    baud_rate:parseInt(document.getElementById('s-baud').value)"
"  };"
"  settings=s;"
"  await fetch('/api/settings',{method:'POST',"
"    headers:{'Content-Type':'application/json'},"
"    body:JSON.stringify(s)});"
"  showToast('Settings saved!');"
"}"

// ── Init ──
"function showConfirm(msg,onOk){"
"  var m=document.getElementById('modal');"
"  document.getElementById('modal-msg').textContent=msg;"
"  m.style.display='flex';"
"  document.getElementById('modal-ok').onclick=function(){"
"    m.style.display='none';onOk();"
"  };"
"  document.getElementById('modal-cancel').onclick=function(){"
"    m.style.display='none';"
"  };"
"}"
"refreshStatus();"
"setInterval(refreshStatus,3000);"
"loadSettings();"
"document.addEventListener('visibilitychange',function(){"
"  if(document.visibilityState==='visible'){"
"    refreshStatus();"
"  }"
"});"
"window.addEventListener('focus',function(){"
"  refreshStatus();"
"});"
"</script>"
"</body></html>";
